CREATE course:00531 SET
    name = "Discrete Math for Computer Science",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 1200,
    req_group = 010024,
    description = "This course provides a rigorous treatment of topics from discrete mathematics which are essential to computer science. Principal topics include: formal logic (propositional & predicate), set theory, proof techniques, mathematical induction, program correctness, combinatorics, discrete probability, relations, functions, matrices, and graph theory. Prerequisite: A grade of \"C\" or better in either Comp Sci 1500 or Comp Sci 1570 and in one of Math 1120, Math 1140, Math 1208, Math 1210, Math 1211, or Math 1214."
;

CREATE course:000524 SET
    name = "Intro to C++ Programming",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 1570,
    req_group = 010712,
    description = "Object-Oriented Programming design and development in C++. Emphasis placed on good programming practices. Topics include syntax/semantics, operators, control flow/decision branching, memory management, functions, file I/O, C-strings, arrays, pointers, classes, templates, inheritance, polymorphism, and exception handling. This course is programming intensive. Prerequisites: A grade of \"C\" or better in Comp Sci 1500 or in both of Comp Sci 1971 and Comp Sci 1981, and accompanied by Comp Sci 1580."
;
CREATE course:000525 SET
    name = "Intro To Programming Lab",
    min_units = 1,
    max_units = 1,
    subjects = "Computer Science",
    catalog_num = 1580,
    req_group = 010713,
    description = "Practical applications of concepts learned in Computer Science 1570. Hands-on instruction in C++ developing, debugging, and testing programming projects. Prerequisite: Accompanied by Comp Sci 1570."
;
CREATE course:000530 SET
    name = "Data Structures",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 1575,
    req_group = 010023,
    description = "A continuation of Object-Oriented Programming, with emphasis on the efficient organization of data through Abstract Data Types and Data Structures. Topics include Linked Lists, Vectors, Stacks, Queues, Trees, Hash Tables, Graphs and their use in a variety of algorithms. Recursive programming techniques are also covered. This course is programming intensive. Prerequisite: Grade of \"C\" or better in Comp Sci 1570."
;
CREATE course:301341 SET
    name = "Data Structures Lab",
    min_units = 1,
    max_units = 1,
    subjects = "Computer Science",
    catalog_num = 1585,
    req_group = 011386,
    description = "Hands-on instruction in programming development tools such as version control systems, integrated development environments, debuggers, profilers, and event-based programming environments. Exercises will complement the concepts presented in Comp Sci 1575. Prerequisite: Preceded or accompanied by Comp Sci 1575."
;
CREATE course:000554 SET
    name = "Theory of Computer Science",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 2200,
    req_group = 010034,
    description = "This course will cover the theoretical underpinnings of computer science. In particular, this course will cover the following topics: basic computability and formal language concepts, regular languages, context free languages, recursively-enumerable languages, and classes P, NP, and NP-completeness. Prerequisite: A grade of \"C\" or better in both Comp Sci 1200 and Comp Sci 1575."
;
CREATE course:000538 SET
    name = "File Structures and Introduction to Database Systems",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 2300,
    req_group = 010027,
    description = "Course covers major topics in file structures and database systems including techniques for disk access and organization, record and file structures, index structures, sequential file, dense/sparse and secondary indexes, B-trees, range queries, insertion/deletion, hash tables, fundamentals of database systems, the ER model, relational model, algebra and SQL. Prerequisite: A grade of \"C\" or better in Comp Sci 1575."
;
CREATE course:000539 SET
    name = "Algorithms",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 2500,
    req_group = 010028,
    description = "Students will solve recurrence relations, analyze algorithms for correctness and time/space complexity, apply these analysis techniques to fundamental dynamic programming, greedy, shortest-path, minimal spanning trees, and maximum flow algorithms and validate these analyses through programming. Prerequisite: A grade of \"C\" or better in both Comp Sci 1200 and Comp Sci 1575; preceded or accompanied by a grade of \"C\" or better in either Math 1208, Math 1211, or Math 1214."
;
CREATE course:000537 SET
    name = "Programming Languages and Translators",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 3500,
    req_group = 010026,
    description = "Covers basic design of programming languages, compilers and interpreters. The concepts of syntax, variables, expressions, types, scope, functions, procedures, statements, I/O, exception handling and concurrency are introduced. The manner in which various programming languages handle these concepts is discussed. Prerequisite: A \"C\" or better grade in Comp Sci 2200."
;
CREATE course:000564 SET
    name = "Introduction to Computer Networks",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 3610,
    req_group = 010036,
    description = "This course covers general principles of computer networking, focusing primarily on internet protocols. It covers the TCP/IP stack, with the application layer first, moving down through link and physical layers. Topics include network virtualization, security, wireless, and mobile networks, with extensive live protocol analysis. Coursework is project based. Prerequisites: A grade of \"C\" or better in Comp Sci 3800."
;
CREATE course:000541 SET
    name = "Introduction to Operating Systems",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 3800,
    req_group = 010029,
    description = "This course teaches the concepts, structure, and mechanisms of Operating Systems. Topics include process management, concurrency, synchronization, deadlock, multithreading, memory management, scheduling, and internetworking. Special emphasis is given to Unix and its modern-day derivatives. Prerequisites: A grade of \"C\" or better in both Comp Sci 1575 and Comp Eng 2210."
;
CREATE course:300624 SET
    name = "Computer Security",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 4610,
    req_group = 010720,
    description = "This course covers principles of threat-modeling, trust, and security policies. Topics include cryptography, reverse engineering, software security, malware analysis, authentication, access controls, operating systems hardening, virtualization, database security, and network security. This class is programming intensive and project based, with case-analyses. Prerequisites: A grade of \"C\" or better in Comp Sci 3610."
;
CREATE course:301525 SET
    name = "SE Capstone I",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 4090,
    req_group = 011450,
    description = "This is the first course in the Software Engineering Capstone sequence covering the Software Life Cycle. Students will learn about software engineering, and work in teams to spec, design, prototype, implement, test, document, deploy, and maintain a software system. This course is programming intensive, writing emphasized and addresses ethical considerations. Prerequisites: A grade of \"C\" or better in all of Comp Sci 2300, Comp Sci 2500, and Comp Sci 3610."
;

CREATE course:301526 SET
    name = "SE Capstone II",
    min_units = 3,
    max_units = 3,
    subjects = "Computer Science",
    catalog_num = 4091,
    req_group = 011451,
    description = "This is the second course in the Software Engineering Capstone sequence covering the Software Life Cycle. Students will learn about software engineering, and work in teams to spec, design, prototype, implement, test, document, deploy and maintain a software system. This course is programming intensive, writing emphasized and addresses ethical considerations. Prerequisites: A grade of \"C\" or better in both Comp Sci 4090 and Comp Sci 4610, and proceeded or accompanied by one of Philos 3225, Philos 3235, Philos 4340 or Philos 4368."
;